ALTER TABLE usuarios
  MODIFY COLUMN tipo_usuario ENUM('ADMIN', 'TREINADOR', 'ALUNO') NOT NULL,
  ADD COLUMN IF NOT EXISTS versao_sessao INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE treinadores
  ADD COLUMN IF NOT EXISTS status ENUM('PENDENTE', 'APROVADO', 'REPROVADO', 'SUSPENSO') NOT NULL DEFAULT 'PENDENTE',
  ADD COLUMN IF NOT EXISTS justificativa_analise TEXT NULL,
  ADD COLUMN IF NOT EXISTS analisado_em DATETIME NULL,
  ADD COLUMN IF NOT EXISTS analisado_por BIGINT NULL,
  ADD COLUMN IF NOT EXISTS criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

UPDATE treinadores SET status = 'APROVADO' WHERE ativo = 1;

CREATE TABLE IF NOT EXISTS logs_administrativos (
  id_log BIGINT NOT NULL AUTO_INCREMENT,
  id_admin BIGINT NOT NULL,
  id_usuario_alvo BIGINT NOT NULL,
  acao ENUM('APROVAR_TREINADOR', 'REPROVAR_TREINADOR', 'SUSPENDER_TREINADOR', 'REATIVAR_TREINADOR') NOT NULL,
  justificativa TEXT NOT NULL,
  estado_anterior JSON NULL,
  estado_novo JSON NULL,
  criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id_log),
  INDEX idx_logs_admin_criado (id_admin, criado_em),
  INDEX idx_logs_alvo_criado (id_usuario_alvo, criado_em)
);
